######################## default configuration ####################
baseURL = "https://www.tanchen.net"
title = "Tan Chen Resources"
theme = "bigspring-light"
defaultContentLanguage = "zh"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "18"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true
