# main menu
[[main]]
name = "首页"
url = "/"
weight = 1

[[main]]
name = "产品中心"
url = "blog/"
weight = 2

[[main]]
name = "铁矿石"
parent = "产品中心"
url = "/blog/iron"
weight = 6

[[main]]
name = "铬铁矿石"
parent = "产品中心"
url = "/blog/ferrochrome"
weight = 7

[[main]]
name = "铝土矿石"
parent = "产品中心"
url = "/blog/bauxite"
weight = 8

[[main]]
name = "铝矿石"
parent = "产品中心"
url = "/blog/aluminum"
weight = 8

[[main]]
name = "铬矿石"
parent = "产品中心"
url = "/blog/chromium"
weight = 8
# [[main]]
# name = "产品"
# url = "pricing/"
# weight = 3

[[main]]
name = "服务"
url = "/faq"
weight = 5

[[main]]
name = "联系我们"
url = "contact/"
weight = 4


# footer menu left
[[footer_left]]
name = "关于我们"
url = "contact"

[[footer_left]]
name = "联系我们"
url = "contact/"


# footer menu middle
[[footer_middle]]
name = "铁矿石"
url = "/blog/iron"

[[footer_middle]]
name = "铬铁矿石"
url = "blog/ferrochrome"

[[footer_middle]]
name = "铝土矿石"
url = "blog/bauxite"

[[footer_middle]]
name = "铝矿石"
url = "blog/aluminum"
[[footer_middle]]
name = "铬矿石"
url = "blog/chromium"
# footer menu right
[[footer_right]]
name = "隐私政策"
url = "privacy-policy/"
